<?xml version="1.0" ?>
<!--

Author: Jonathan Sprinkle, Sam Taylor, Alex Warren
Copyright (c) 2013-2016 Arizona Board of Regents
All rights reserved.

Permission is hereby granted, without written agreement and without 
license or royalty fees, to use, copy, modify, and distribute this
software and its documentation for any purpose, provided that the 
above copyright notice and the following two paragraphs appear in 
all copies of this software.

IN NO EVENT SHALL THE ARIZONA BOARD OF REGENTS BE LIABLE TO ANY PARTY 
FOR DIRECT, INDIRECT, SPECIAL, INCIDENTAL, OR CONSEQUENTIAL DAMAGES 
ARISING OUT OF THE USE OF THIS SOFTWARE AND ITS DOCUMENTATION, EVEN 
IF THE ARIZONA BOARD OF REGENTS HAS BEEN ADVISED OF THE POSSIBILITY OF 
SUCH DAMAGE.

THE ARIZONA BOARD OF REGENTS SPECIFICALLY DISCLAIMS ANY WARRANTIES, 
INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY 
AND FITNESS FOR A PARTICULAR PURPOSE. THE SOFTWARE PROVIDED HEREUNDER
IS ON AN "AS IS" BASIS, AND THE ARIZONA BOARD OF REGENTS HAS NO OBLIGATION
TO PROVIDE MAINTENANCE, SUPPORT, UPDATES, ENHANCEMENTS, OR MODIFICATIONS.

Summary: 
=======
This launch file loads the worlds and models for the catvehicle

How to execute it:
=================
roslaunch catvehicle catvehicle_skidpan.launch

-->

<!-- Inertial parameters selected with the help of 
http://www.car-engineer.com/vehicle-inertia-calculation-tool/
-->

<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="catvehicle">
  
  <xacro:property name="PI" value="3.1415926835897931"/>
<!--  <xacro:property name="base_height" value="0"/> -->
  <xacro:property name="base_height" value="1.0639"/>
  <xacro:property name="base_mass" value="2050"/>
  <xacro:property name="base_mass_ixx" value="63"/>
  <xacro:property name="base_mass_iyy" value="1048"/>
  <xacro:property name="base_mass_izz" value="1111"/>
  <xacro:property name="base_mass_ixz" value="-31"/>
  <xacro:property name="tyre_x" value="1.31"/>
  <xacro:property name="tyre_y" value="0.765"/>
  <xacro:property name="tyre_length" value="0.229"/>
  <xacro:property name="tyre_r" value="0.66"/>
  <xacro:property name="tyre_radius" value="0.356"/>
  <xacro:property name="tyre_mass" value="40"/>
  <xacro:property name="tyre_mass_ixx" value="54"/>
  <xacro:property name="tyre_mass_iyy" value="56"/>
  <xacro:property name="tyre_mass_izz" value="104"/>
  <xacro:property name="car_height" value="1.4478"/>
  <xacro:property name="car_to_bumper" value="2.4"/>
  <xacro:property name="front_bumper_height" value="${car_height/2}"/>
  <xacro:property name="sensor_box" value="0.25"/>
  <xacro:property name="sensor_box2" value="0.01"/>
  <xacro:property name="camera_box" value="0.1"/>
  <xacro:property name="tyre_height" value="-0.696"/>
  <xacro:property name="str_length" value="0.01"/>
  <xacro:property name="str_radius" value="0.1"/>
  <xacro:property name="str_angle" value="0.6"/>
  <xacro:property name="car_width" value="1.301"/>
  <xacro:property name="front_laser_points" value="$(arg front_laser_points)"/>
  <xacro:property name="front_top_lidar_points" value="$(arg front_top_lidar_points)"/>
  <xacro:property name="velodyne_points" value="$(arg velodyne_points)"/>
  <xacro:property name="camera_right" value="$(arg camera_right)"/>
  <xacro:property name="camera_left" value="$(arg camera_left)"/>
  <xacro:property name="tyre_origin">
	<origin xyz="0 0 0" rpy="${PI/2} 0 0"/>
  </xacro:property>
  <xacro:property name="tyre_origin_2">
        <origin xyz="0 0 0" rpy="0 0 ${PI/2}"/>
  </xacro:property>
  <xacro:property name="tyre_origin_3">
        <origin xyz="0 0 0" rpy="0 0 ${-PI/2}"/>
  </xacro:property>
  
    <xacro:include filename="$(find catvehicle)/urdf/catvehicle.gazebo"/>

    <xacro:if value="${front_laser_points}">
    	<xacro:include filename="$(find catvehicle)/urdf/catvehicle_front_laser_points.gazebo"/>
    </xacro:if>
    <xacro:if value="${front_top_lidar_points}">
    	<xacro:include filename="$(find catvehicle)/urdf/catvehicle_front_top_lidar_points.gazebo"/>
    </xacro:if>
    <xacro:if value="${velodyne_points}">
    	<xacro:include filename="$(find catvehicle)/urdf/catvehicle_velodyne_points.gazebo"/>
    </xacro:if>

    <xacro:if value="${camera_right}">
    	<xacro:include filename="$(find catvehicle)/urdf/catvehicle_right_camera.gazebo"/>
    </xacro:if>
    <xacro:if value="${camera_left}">
    	<xacro:include filename="$(find catvehicle)/urdf/catvehicle_left_camera.gazebo"/>
    </xacro:if>




<!--Car Body-->





<link name="base_link">
    <collision>
         <origin xyz="0 0 ${base_height}" rpy="0 0 0"/>  
           <geometry>
            <box size="2.62 ${car_width} ${car_height}"/>
        </geometry>
      </collision>
     <visual>
        <origin xyz="-0.25 0 ${base_height + 0.05}" rpy="0 0 0"/>  
        <geometry>
          <mesh filename="package://catvehicle/meshes/ford_escape_no_wheels_2.dae"/>
        </geometry>
     </visual>
</link>

<joint name="inertial_joint" type="fixed">
      <parent link="base_link"/>
      <child link="main_mass"/>
      <origin xyz="0 0 0" rpy="0 0 0"/>
</joint>

<link name="main_mass" type="fixed">
     <parent link="inertial_joint"/>
     <inertial>
        <origin xyz="0 0 ${base_height}" rpy="0 0 0"/>
        <mass value="${base_mass}"/>
        <inertia
          ixx="${base_mass_ixx}"  ixy="0.000000" ixz="${base_mass_ixz}"
          iyy="${base_mass_iyy}" iyz="0.000000"
          izz="${base_mass_izz}"/>
      </inertial>
</link>

<!--Back Right Wheel-->




<joint name="back_right_wheel_joint" type="continuous">
      <parent link="base_link"/>
      <child link="back_right_wheel_link"/>
      <origin xyz="${-tyre_x} ${-tyre_y} ${tyre_r}" rpy="0 0 0"/>
      <axis xyz="0 1 0"/>
      <dynamics damping="0.1"/>
     <limit effort="10000" velocity="100" />
      <joint_properties damping="0.0" friction="0.0" />
</joint>

<link name="back_right_wheel_link">
     <collision>
      <xacro:insert_block name="tyre_origin"/>
        <geometry>
         <cylinder length="${tyre_length}" radius="${tyre_radius}"/>
        </geometry>
     </collision>

     <visual>
      <xacro:insert_block name="tyre_origin_3"/>
        <geometry>
          <mesh filename="package://catvehicle/meshes/ford_escape_wheel.dae"/>
      <scale xyz="1.2 1 1"/>
        </geometry>
      </visual>

      <inertial>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <mass value="${tyre_mass}"/>
        <inertia
          ixx="${tyre_mass_ixx}"  ixy="0.000000"  ixz="0.000000"
          iyy="${tyre_mass_iyy}"  iyz="0.000000"
          izz="${tyre_mass_izz}"/>
      </inertial>
</link>




<!--Back Left Wheel-->




<joint name="back_left_wheel_joint" type="continuous">
      <parent link="base_link"/>
      <child link="back_left_wheel_link"/>
      <origin xyz="${-tyre_x} ${tyre_y} ${tyre_r}" rpy="0 0 0"/>
      <axis xyz="0 1 0"/>
      <dynamics damping="0.1"/>
      <limit effort="10000" velocity="100" />
      <joint_properties damping="0.0" friction="0.0" />
</joint>

<link name="back_left_wheel_link">
     <collision>
      <xacro:insert_block name="tyre_origin"/>
        <geometry>
         <cylinder length="0.229" radius="${tyre_radius}"/>
        </geometry>
     </collision>

     <visual>
      <xacro:insert_block name="tyre_origin_2"/>
        <geometry>
          <mesh filename="package://catvehicle/meshes/ford_escape_wheel.dae"/>
          <scale xyz="1.2 1 1"/>
        </geometry>
      </visual>

      <inertial>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <mass value="${tyre_mass}"/>
        <inertia
          ixx="${tyre_mass_ixx}"  ixy="0.000000"  ixz="0.000000"
          iyy="${tyre_mass_iyy}"  iyz="0.000000"
          izz="${tyre_mass_izz}"/>
      </inertial>
</link>



<!--Right Steering-->




<joint name="front_right_steering_joint" type="revolute">
	<parent link="base_link"/>
	<child link="front_right_steering_link"/>
	<origin xyz="${tyre_x} ${-car_width/2 - str_length/2} ${tyre_r}" rpy="0 0 0"/>
        <axis xyz="0 0 1"/>
	<limit effort="1000.0" lower="${-str_angle}" upper="${str_angle}" velocity="0.5"/>
</joint>

<link name="front_right_steering_link">
	<collision>
	      <xacro:insert_block name="tyre_origin"/>
	        <geometry>
        	 <cylinder length="${str_length}" radius="${str_radius}"/>
       		</geometry>
	</collision>

	<visual>
              <xacro:insert_block name="tyre_origin"/>
                <geometry>
                 <cylinder length="${str_length}" radius="${str_radius}"/>
                </geometry>
	</visual>

      <inertial>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <mass value="10.00"/>
        <inertia
          ixx="0.4"  ixy="0.000000"  ixz="0.000000"
          iyy="0.6"  iyz="0.000000"
          izz="0.4"/>
      </inertial>
</link>



<!--Right Front Wheel-->




<joint name="front_right_wheel_joint" type="continuous">
      <parent link="front_right_steering_link"/>
      <child link="front_right_wheel_link"/>
      <origin xyz="0 ${-str_length/2 - tyre_length/2} 0" rpy="0 0 0"/>
      <axis xyz="0 1 0"/>
</joint>

<link name="front_right_wheel_link">
     <collision>
      <xacro:insert_block name="tyre_origin"/>
        <geometry>
         <cylinder length="${tyre_length}" radius="${tyre_radius}"/>
	</geometry>
     </collision>

     <visual>
      <xacro:insert_block name="tyre_origin_3"/>
        <geometry>
          <mesh filename="package://catvehicle/meshes/ford_escape_wheel.dae"/>
        <scale xyz="1.2 1 1"/>
       </geometry>  
      </visual>

      <inertial>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <mass value="${tyre_mass}"/>
        <inertia
          ixx="${tyre_mass_ixx}"  ixy="0.000000"  ixz="0.000000"
          iyy="${tyre_mass_iyy}"  iyz="0.000000"
          izz="${tyre_mass_izz}"/>
      </inertial>
</link>




<!--Left Steering-->



<joint name="front_left_steering_joint" type="revolute">
        <parent link="base_link"/>
        <child link="front_left_steering_link"/>
        <origin xyz="${tyre_x} ${car_width/2 + str_length/2} ${tyre_r}" rpy="0 0 0"/>
        <axis xyz="0 0 1"/>
        <limit effort="1000.0" lower="${-str_angle}" upper="${str_angle}" velocity="0.5"/>
</joint>

<link name="front_left_steering_link">
      <parent link="base_link"/>
        <collision>
              <xacro:insert_block name="tyre_origin"/>
                <geometry>
                 <cylinder length="${str_length}" radius="${str_radius}"/>
                </geometry>
        </collision>

        <visual>
              <xacro:insert_block name="tyre_origin"/>
                <geometry>
                 <cylinder length="${str_length}" radius="${str_radius}"/>
                </geometry>
        </visual>

      <inertial>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <mass value="10.00"/>
        <inertia
          ixx="0.4"  ixy="0.000000"  ixz="0.000000"
          iyy="0.6"  iyz="0.000000"
          izz="0.4"/>
      </inertial>
</link>



<!--Front Right Wheel-->



<joint name="front_left_wheel_joint" type="continuous">
      <parent link="front_left_steering_link"/>
      <child link="front_left_wheel_link"/>
      <origin xyz="0 ${str_length/2 + tyre_length/2} 0" rpy="0 0 0"/>
      <axis xyz="0 1 0"/>

      <dynamics damping="0.1"/>
      <limit effort="10000" velocity="100" />
      <joint_properties damping="0.0" friction="0.0" />

</joint>


<link name="front_left_wheel_link">
     <parent link="front_left_wheel_joint"/>
     <collision>     
	<origin xyz="0 0 0" rpy="${PI/2} 0 0"/>
        <geometry>
         <cylinder length="0.229" radius="${tyre_radius}"/>
        </geometry>
     </collision>

     <visual>
      <xacro:insert_block name="tyre_origin_2"/>
       <geometry>
          <mesh filename="package://catvehicle/meshes/ford_escape_wheel.dae"/>
            <scale xyz="1.2 1 1"/>
       </geometry>
      </visual>

      <inertial>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <mass value="${tyre_mass}"/>
        <inertia
          ixx="${tyre_mass_ixx}"  ixy="0.000000"  ixz="0.000000"
          iyy="${tyre_mass_iyy}"  iyz="0.000000"
          izz="${tyre_mass_izz}"/>
      </inertial>
</link>



<!-- Cameras-->

<joint name="camera_right_joint" type="fixed">
<origin xyz="-0.75 -${car_width/2} ${0.725 + camera_box/2 + 1.25}" rpy="0 0 -${PI/2}"/>
	<axis xyz="0 0 1"/>
	<parent link="base_link"/>
	<child link="camera_right_link"/>
</joint>

<link name="camera_right_link">
	<collision>
	  <origin xyz="0 0 0" rpy="0 0 0"/>
	  <geometry>
	   <box size="${camera_box} ${camera_box} ${camera_box}"/>
	  </geometry>
	</collision>

	<visual>
	  <origin xyz="0 0 0" rpy="0 0 0"/>
	  <geometry>
	  <box size="${camera_box} ${camera_box} ${camera_box}"
/>
          </geometry>
	</visual>

    <inertial>
      <mass value="1e-5" />
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <inertia ixx="1e-6" ixy="0" ixz="0" iyy="1e-6" iyz="0" izz="1e-6" />
    </inertial>
</link>

<joint name="camera_left_joint" type="fixed">
<origin xyz="-0.75 ${car_width/2} ${0.725 + camera_box/2 + 1.25}" rpy="0 0 ${PI/2}"/>
	<axis xyz="0 0 1"/>
	<parent link="base_link"/>
	<child link="camera_left_link"/>
</joint>

<link name="camera_left_link">
	<collision>
	  <origin xyz="0 0 0" rpy="0 0 0"/>
	  <geometry>
	   <box size="${camera_box} ${camera_box} ${camera_box}"/>
	  </geometry>
	</collision>

	<visual>
	  <origin xyz="0 0 0" rpy="0 0 0"/>
	  <geometry>
	  <box size="${camera_box} ${camera_box} ${camera_box}"
/>
          </geometry>
	</visual>

    <inertial>
      <mass value="1e-5" />
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <inertia ixx="1e-6" ixy="0" ixz="0" iyy="1e-6" iyz="0" izz="1e-6" />
    </inertial>
</link>


<!--joint name="camera_joint" type="fixed">
<origin xyz="0 0 ${0.725 + sensor_box/2 + 1.25}" rpy="0 0 0"/>
	<axis xyz="0 0 1"/>
	<parent link="base_link"/>
	<child link="camera_link"/>
</joint>

<link name="camera_link">
	<collision>
	  <origin xyz="0 0 0" rpy="0 0 0"/>
	  <geometry>
	   <box size="${sensor_box} ${sensor_box} ${sensor_box}"/>
	  </geometry>
	</collision>

	<visual>
	  <origin xyz="0 0 0" rpy="0 0 0"/>
	  <geometry>
	  <box size="${sensor_box} ${sensor_box} ${sensor_box}"
/>
          </geometry>
	</visual>

    <inertial>
      <mass value="1e-5" />
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <inertia ixx="1e-6" ixy="0" ixz="0" iyy="1e-6" iyz="0" izz="1e-6" />
    </inertial>
</link-->



<!--Velodyne LIDAR-->



<!--joint name="velodyne_joint" type="fixed">
	<origin xyz="0 0 ${sensor_box/2 + 0.01}" rpy="0 0 0"/>
	<axis xyz="0 0 1"/>
	<parent link="camera_link"/>
	<child link="velodyne_link"/>
</joint>

<link name="velodyne_link">
        <collision>
          <origin xyz="0 0 0" rpy="0 0 0"/>
          <geometry>
           <box size="${sensor_box} ${sensor_box} ${sensor_box}"/>
          </geometry>
        </collision>

        <visual>
          <origin xyz="0 0 0" rpy="0 0 0"/>
          <geometry>
           <mesh filename="package://catvehicle/meshes/hokuyo.dae"/>
          </geometry>
        </visual>

    <inertial>
      <mass value="1e-5" />
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <inertia ixx="1e-6" ixy="0" ixz="0" iyy="1e-6" iyz="0" izz="1e-6" />
    </inertial>
</link-->

<joint name="front_laser_joint" type="fixed">
	<origin xyz="${car_to_bumper} 0 ${front_bumper_height + sensor_box/2 + 0.01}" rpy="0 0 0"/>
	<axis xyz="0 0 1"/>
	<parent link="base_link"/>
	<child link="front_laser_link"/>
</joint>

<link name="front_laser_link">
     <parent link="front_laser_joint"/>
        <collision>
          <origin xyz="0 0 0" rpy="0 0.0 0"/>
          <geometry>
           <box size="${sensor_box} ${sensor_box} ${sensor_box}"/>
          </geometry>
        </collision>

        <visual>
          <origin xyz="0 0 0" rpy="0 0 0"/>
          <geometry>
           <box size="${sensor_box} ${sensor_box} ${sensor_box}"/>
          </geometry>
        </visual>

    <inertial>
      <mass value="1e-5" />
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <inertia ixx="1e-6" ixy="0" ixz="0" iyy="1e-6" iyz="0" izz="1e-6" />
    </inertial>
</link>

<joint name="front_top_lidar_joint" type="fixed">
	<!--origin xyz="${car_to_bumper} 0 ${front_bumper_height + sensor_box/2 + 0.01}" rpy="0 0 0"/-->
        <origin xyz="0.5 0 ${0.725 + sensor_box/2 + 1.25}" rpy="0 0.261799 0"/>
	<axis xyz="0 0 1"/>
	<parent link="base_link"/>
	<child link="front_top_lidar"/>
</joint>

<link name="front_top_lidar">
     <parent link="front_top_lidar_joint"/>
        <collision>
          <origin xyz="0 0 0" rpy="0 0.0 0"/>
          <geometry>
           <box size="${sensor_box} ${sensor_box} ${sensor_box}"/>
          </geometry>
        </collision>

        <visual>
          <origin xyz="0 0 0" rpy="0 0 0"/>
          <geometry>
           <box size="${sensor_box} ${sensor_box} ${sensor_box}"/>
          </geometry>
        </visual>

    <inertial>
      <mass value="1e-5" />
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <inertia ixx="1e-6" ixy="0" ixz="0" iyy="1e-6" iyz="0" izz="1e-6" />
    </inertial>
</link>

<!-- motors and transmissions for the two rear wheels -->
  <transmission name="tran1">
    <type>transmission_interface/SimpleTransmission</type>
    <joint name="back_right_wheel_joint">
      <hardwareInterface>VelocityJointInterface</hardwareInterface>
    </joint>
    <actuator name="motor1">
      <hardwareInterface>VelocityJointInterface</hardwareInterface>
      <mechanicalReduction>1</mechanicalReduction>
    </actuator>
  </transmission>

  <transmission name="tran2">
    <type>transmission_interface/SimpleTransmission</type>
    <joint name="back_left_wheel_joint">
      <hardwareInterface>VelocityJointInterface</hardwareInterface>
    </joint>
    <actuator name="motor2">
      <hardwareInterface>VelocityJointInterface</hardwareInterface>
      <mechanicalReduction>1</mechanicalReduction>
    </actuator>
  </transmission>

  <transmission name="rack_and_pinion_left">
    <type>transmission_interface/SimpleTransmission</type>
    <joint name="front_left_steering_joint">
      <hardwareInterface>PositionJointInterface</hardwareInterface>
    </joint>
    <actuator name="eps_left">
      <hardwareInterface>PositionJointInterface</hardwareInterface>
      <mechanicalReduction>1</mechanicalReduction>
    </actuator>
  </transmission>

  <transmission name="rack_and_pinion_right">
    <type>transmission_interface/SimpleTransmission</type>
    <joint name="front_right_steering_joint">
      <hardwareInterface>PositionJointInterface</hardwareInterface>
    </joint>
    <actuator name="eps_right">
      <hardwareInterface>PositionJointInterface</hardwareInterface>
      <mechanicalReduction>1</mechanicalReduction>
    </actuator>
  </transmission>

</robot>
